channels:
  - conda-forge

dependencies:
  - python=3.7.3
  - pip
  - pip:
    - jupyter
    - numpy
    - pandas
    - scikit-learn
    - matplotlib
    - opencv-python
    - seaborn
    - pydub
    - tensorflow
    - tensorflow_io
    - tensorflow_datasets