channels:
  - conda-forge

dependencies:
  - python=3.7.3
  - tensorflow-gpu
  - pip
  - pip:
    - jupyter
    - numpy
    - pandas
    - scikit-learn
    - matplotlib
    - opencv-python
    - seaborn